### ISSUE TITLE
Support pages functions deployment

### ISSUE THREAD

**Issue by EresDev** [ubiquity/cloudflare-deploy-action#12]
We have started to use [Cloudflare pages function](https://developers.cloudflare.com/pages/functions/) in https://github.com/ubiquity/pay.ubq.fi/pull/226 . **cloudflare-deploy-action** does not support the deployment of pages function. It only deploys static files.

For pages functions to work, it is necessary to have functions files in a `functions` directory. This directory must be the one where we run `wrangler pages deploy`. It appears when this action runs the `wrangler pages deploy`, the current directory is not where the `functions` directory is present.

For this to work, the cloudflare-deploy-action needs some changes but it also must support whatever is working already in static-only projects.

**Comment by 0x4007** [comment]
I'm assuming that a "backend" is unavoidable in some situations due to auth but let's discuss [here](https://github.com/ubiquity/pay.ubq.fi/pull/226#issuecomment-2108907609).
