### ISSUE TITLE
Output deployment URL

### ISSUE THREAD

**Issue by rndquu** [ubiquity/cloudflare-deploy-action#4]
Original [comment](https://github.com/ubiquity/onboard.ubq.fi/pull/10#issuecomment-1993847541)

We should pass cloudflare deployment preview to cypress workflow [here](https://github.com/ubiquity/onboard.ubq.fi/blob/b4f41babfd0898cb1ce6a2a1885a186844a686ab/.github/workflows/cypress-testing.yml#L25).

What should be done:
1. Update current github action to return deployment URL in [output](https://github.com/ubiquity/pay.ubq.fi/blob/ea00b8db59c82e015bfbaf9652dd072bbb237d4e/.github/workflows/continuous-deploy.yml#L55) (example)
2. Update all ubiquity repos which use [cypress workflow](https://github.com/ubiquity/onboard.ubq.fi/blob/b4f41babfd0898cb1ce6a2a1885a186844a686ab/.github/workflows/cypress-testing.yml) and set `FRONTEND_URL` env variable to https://github.com/ubiquity/cloudflare-deploy-action output

**Comment by 0x4007** [comment]
Prob should be high priority if it's CI for all repos

**Comment by rndquu** [comment]
> Prob should be high priority if it's CI for all repos

I'll fix it as part of https://github.com/ubiquity/cloudflare-deploy-action/issues/1, this issue more of a reminder

**Comment by 0xJoichiro** [comment]
@rndquu is this issue finished in #1 ?

**Comment by rndquu** [comment]
> @rndquu is this issue finished in #1 ?

No, you're free to take it

**Comment by 0xJoichiro** [comment]
> > @rndquu is this issue finished in #1 ?
> 
> No, you're free to take it

understood,how should i test the same?

**Comment by 0xJoichiro** [comment]
We can start with getting DEPLOYMENT_URL from the bash script for deploying to cloudflare https://github.com/ubiquity/cloudflare-deploy-action/blob/5454d2d0d1a8efc44ff894825605b03f109f8986/.github/cloudflare-deploy.sh#L39

Set an output up for downstream actions 

```yaml
        echo "::set-output name=deploy_url::${{ env.DEPLOYMENT_URL }}"
```
Then could get that back as an output from something like [here](https://github.com/ubiquity/onboard.ubq.fi/blob/b4f41babfd0898cb1ce6a2a1885a186844a686ab/.github/workflows/build.yml#L35)
 => 

```yaml
       url: ${{steps.deploy.outputs.deploy_url}}

```

please confirm this logic and i'll make the PR asap

**Comment by rndquu** [comment]
> We can start with getting DEPLOYMENT_URL from the bash script for deploying to cloudflare
> 
> https://github.com/ubiquity/cloudflare-deploy-action/blob/5454d2d0d1a8efc44ff894825605b03f109f8986/.github/cloudflare-deploy.sh#L39
> 
> Set an output up for downstream actions
> 
> ```yaml
>         echo "::set-output name=deploy_url::${{ env.DEPLOYMENT_URL }}"
> ```
> 
> Then could get that back as an output from something like [here](https://github.com/ubiquity/onboard.ubq.fi/blob/b4f41babfd0898cb1ce6a2a1885a186844a686ab/.github/workflows/build.yml#L35) =>
> 
> ```yaml
>        url: ${{steps.deploy.outputs.deploy_url}}
> ```
> 
> please confirm this logic and i'll make the PR asap

Sounds good

**Comment by rndquu** [comment]
> > > @rndquu is this issue finished in #1 ?
> > 
> > 
> > No, you're free to take it
> 
> understood,how should i test the same?

Not sure what you mean by "test the same"

**Comment by 0xJoichiro** [comment]
> > > > @rndquu is this issue finished in #1 ?
> > > 
> > > 
> > > No, you're free to take it
> > 
> > 
> > understood,how should i test the same?
> 
> Not sure what you mean by "test the same"

I meant to ask,how would we test this workflow in action?

**Comment by rndquu** [comment]
> > > > > @rndquu is this issue finished in #1 ?
> > > > 
> > > > 
> > > > No, you're free to take it
> > > 
> > > 
> > > understood,how should i test the same?
> > 
> > 
> > Not sure what you mean by "test the same"
> 
> I meant to ask,how would we test this workflow in action?

Test locally first (i.e. in one of your workflows)

**Comment by rndquu** [comment]
@gentlementlegen It seems we may close this one as "not planned" since deployment URL may be fetched from [env variable](https://github.com/ubiquity/cloudflare-deploy-action/blob/f7d1d691b02b6026e5cf520cb5a86e0bf9701834/.github/cloudflare-deploy.sh#L49) + cypress seems to be working fine [locally](https://github.com/ubiquity/pay.ubq.fi/blob/63ec9832eec11c7496dc1b34c48e267c23ba3856/.github/workflows/cypress-testing.yml#L56)

**Comment by gentlementlegen** [comment]
Agreed, and so far we've been able to fake auth even within Cypress for projects like `work.ubq.fi` so this is no relevant for now.
