### ISSUE TITLE
CI: refactor `pull_request_target` to `pull_request`

### ISSUE THREAD

**Issue by rndquu** [ubiquity/cloudflare-deploy-action#6]
Right now we're using `pull_request_target` in many places like:
- https://github.com/ubiquity/ubiquibot-kernel/blob/c553d5a7866c1ef76d4f589d8095c8bb751cbd49/.github/workflows/bun-testing.yml#L4
- https://github.com/ubiquity/ts-template/blob/84d03ca4fef2d5cf1ecff4bf1333e56895685151/.github/workflows/jest-testing.yml#L4

In the examples mentioned above workflows always check out the `development` branch + open a security hole for exfiltrating of github access token with write permissions.

Check this for more info:
- https://github.com/ubiquity/keygen.ubq.fi/pull/5#discussion_r1530367166
- https://github.com/ubiquity/cloudflare-deploy-action/issues/1#issuecomment-1999654318

What should be done:
- refactor all CI workflows in the https://github.com/ubiquity organization from `pull_request_target` to `pull_request`
- fix related CI errors where necessary

**Comment by gentlementlegen** [comment]
@rndquu I believe it is arbitrary that you opened this issue in the repository since it impact plenty of them. Maybe would make more sense to open it at https://github.com/ubiquity/ts-template ?

**Comment by 0x4007** [comment]
> @rndquu I believe it is arbitrary that you opened this issue in the repository since it impact plenty of them. Maybe would make more sense to open it at https://github.com/ubiquity/ts-template ?

I think its related to deploys which technically has code spanning across the ts-template and every repository as an extension of the template. However this repository I think makes the most sense for deploys related tasks.

**Comment by gitcoindev** [comment]
Hi @gentlementlegen good luck! I encountered a chicken-and-egg problem for Knip reporter part here: https://github.com/ubiquity/keygen.ubq.fi/pull/5#discussion_r1530367166 , still experimenting on that..

**Comment by gitcoindev** [comment]
You may want to read a few links from that thread. Basically, for branches across the same repository it does work correctly with pull_request, https://github.com/gitcoindev/keygen.ubq.fi/actions/runs/8355152504

In case of `pull_request` workflow opened from a forked repository , the `secrets` are not passed (all of the variables are `None` / null`) , there are ways to deal with this but I have not found the perfect solution, yet.

**Comment by gitcoindev** [comment]
My last version that 'almost works' is to use pull_request_workflow and a fine grained token https://github.com/korrrba/keygen.ubq.fi/actions/runs/8366591693/workflow , see  tibdex/github-app-token@v2.1.0 . But perhaps I leave more investigation to you, you may discover something that works better. For the deploy workflow @rndquu was able to solve it in an elegant way, building with read only permissions and deploying with the elevated ones.

**Comment by gentlementlegen** [comment]
@gitcoindev Thanks not very reassuring haha. That is correct, forks are not receiving the secrets for security purposes. `pull-request-target` sort of solved it but uses the base branch for the workflows and introduces security issues where the secrets can be leaked. I thought of a few workarounds. Because I think we will always need to use secrets at some point, even for testing.

The main reason why we require the secrets is also to post to the current PR the results. This could eventually be disabled, and we would still notice that the workflow failed to run. But in the case of testing, if credentials are needed, we obiously cannot expose them. I thought maybe we should either:
- always require to have a link to a successful build (which is what we kinda do now), it's functional but wouldn't block a pull request and we still could merge by accident
- trigger the workflow but not in the PR, rather on a push to the dev branch or something similar. In that way, the workflows would get the secrets, and we would still detect a merge that broke stuff. This however could make reverts also very difficult in some scenarios.

**Comment by gitcoindev** [comment]
Yes I have similar conclusions. By the way in one of the articles I found a hack that allows to workaround for `uses the base branch for the workflows ` default scenario:

```
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```

When the `github.event.pull_request` is available, head.sha can be used to fetch the pull request workspace instead of the base branch.

**Comment by gentlementlegen** [comment]
Doesn't this introduce the security breach that @rndquu had been mentioning before?

**Comment by 0x4007** [comment]
To simplify permissions what if we just use `github-actions[bot]` or whatever the default is, and then focus on annotations in files view instead of comments?

**Comment by gentlementlegen** [comment]
> To simplify permissions what if we just use `github-actions[bot]` or whatever the default is, and then focus on annotations in files view instead of comments?

Wouldn't solve scenarios requiring keys or credentials

**Comment by gitcoindev** [comment]
> To simplify permissions what if we just use `github-actions[bot]` or whatever the default is, and then focus on annotations in files view instead of comments?

I also thought about this approach, but for the Knip case two write permissions are needed:

```
permissions:
  checks: write
  issues: write
```

If we skip comments, `Checks: write` is the blocking one as well.  I began to wonder if there is a completely another way to tackle this like rewriting the knip-reporter to not to use checks -) I hope that @gentlementlegen can come up with a better solution.

**Comment by gitcoindev** [comment]
There is a quite long thread in GitHub actions repository, https://github.com/actions/checkout/issues/518

Many projects struggle with that. One of the last comments mentions the similar workflow that @rndquu introduced:

https://github.com/actions/checkout/issues/518#issuecomment-1972009337

(does not work for Knip-reporter currently though due to https://github.com/Codex-/knip-reporter/blob/main/src/main.ts#L24 and the fact that it complains about `workflow_run`) . Perhaps this can be solved in the knip-reporter somehow.

**Comment by gentlementlegen** [comment]
One solution I thought of as well, is using environments for our secrets to keep using `pull_request_target` but avoid production secrets leak.
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
In the theory we should have a dev environment where everything, even if leaked, are no threat to our production elements. We could have a `development` and `production` environment, each with different secrets.

**Comment by rndquu** [comment]
[This](https://github.com/Codex-/knip-reporter/blob/1d32edf5aecf8728aae419758f2f4b4e35fd6945/src/main.ts#L24) check is introduced because PR number is used [here](https://github.com/Codex-/knip-reporter/blob/1d32edf5aecf8728aae419758f2f4b4e35fd6945/src/main.ts#L47).

The thing is that on `workflow_run` (which runs in a privileged context with access to secrets) we can still fetch associated PR number [this](https://github.com/ubiquity/cloudflare-deploy-action/blob/05cf678961b481e76c21b95679c17ec9d3b33c23/action.yml#L41-L57) way. 

We could update https://github.com/Codex-/knip-reporter/blob/1d32edf5aecf8728aae419758f2f4b4e35fd6945/src/main.ts to work with `workflow_run` with (relatively) small code changes.

**Comment by gentlementlegen** [comment]
> [This](https://github.com/Codex-/knip-reporter/blob/1d32edf5aecf8728aae419758f2f4b4e35fd6945/src/main.ts#L24) check is introduced because PR number is used [here](https://github.com/Codex-/knip-reporter/blob/1d32edf5aecf8728aae419758f2f4b4e35fd6945/src/main.ts#L47).
> 
> The thing is that on `workflow_run` (which runs in a privileged context with access to secrets) we can still fetch associated PR number [this](https://github.com/ubiquity/cloudflare-deploy-action/blob/05cf678961b481e76c21b95679c17ec9d3b33c23/action.yml#L41-L57) way.
> 
> We could update https://github.com/Codex-/knip-reporter/blob/1d32edf5aecf8728aae419758f2f4b4e35fd6945/src/main.ts to work with `workflow_run` with (relatively) small code changes.

This is true, but doesn't solve cases where we need credentials or any other kind of sensitive data (I think mostly about login tests). If we use environments for our secrets we can have workflows like
```GITHUB_TOKEN: ${{ secrets.development.GITHUB_TOKEN }}```
Where the PAT only has very restricted access, such as PR read / post only. This way, we keep secrets, can run any workflow normally and still do not expose any sensitive data.

**Comment by rndquu** [comment]
This all started with https://github.com/Codex-/knip-reporter, I would remove it, keep using plain `yarn knip` in a build workflow (which throws on knip warnings) and be done with that without refactoring https://github.com/Codex-/knip-reporter, introducing environments and other unnecessary stuff

> This is true, but doesn't solve cases where we need credentials

We don't need sensitive credentials anywhere, the only ones I can think of are cloudflare credentials but they are already used [safely](https://github.com/ubiquity/pay.ubq.fi/blob/cd49591bd37a0d616a0d1ea757b9c0e478ae0778/.github/workflows/deploy.yml)

> I think mostly about login tests

I'm sure there is a way to mock github oauth without passing sensitive credentials in a build step

**Comment by gentlementlegen** [comment]
It is not possible to fake the OAuth except if we also run Supabase inside the Action, and setup a whole new DB. Which would also probably require GitHub keys to set the OAuth. I would like not to have any sensitive data in the env, but we should then consider not doing any test requiring authentication, or involving any sensitive data to achieve so

**Comment by gentlementlegen** [comment]
Sorry for necroposting here, but I think this has been mostly resolved as we do not use `pull_request_target` anywhere afaik.

However, for `Knip` we still use the [Workflow Run](https://github.com/ubiquity/ubiquibot-kernel/blob/development/.github/workflows/knip-reporter.yml#L4) to trigger the workflow with the secrets. In the case of Knip, wouldn't it be enough to post the results in the summary the same way we do now for Jest? [Like here for example](https://github.com/ubiquibot/conversation-rewards/actions/runs/10117750922), so we would not need the Knip reporter script.

The only Actions that should require environment variables are the ones requiring secrets for deployments and such, which are currently triggered after the `Build` step is complete so get access to the environment. However I think this is as dangerous as using `pull_request_target`. But without it we would not be able to have preview deployments with Cloudflare like we do for `work.ubq.fi`.

**Comment by 0x4007** [comment]
> Sorry for necroposting here

This is expected and why I like to keep all of our work on GitHub so that we can use all conversations/issues as an archive. 

> wouldn't it be enough to post the results in the summary the same way we do now for Jes

Yes this is preferred so as to not clutter the conversation.

**Comment by rndquu** [comment]
Right now there are only 2 places left which uses `pull_request_target` across `ubiquity` and `ubiquibot` organizations:
- https://github.com/ubiquity/onboard.ubq.fi/blob/902ff2b5c4116044f12fa266a0ab3e44315c0fcb/.github/workflows/knip.yml#L4
- https://github.com/ubiquity/onboard.ubq.fi/blob/902ff2b5c4116044f12fa266a0ab3e44315c0fcb/.github/workflows/cypress-testing.yml#L4

**Comment by gentlementlegen** [comment]
@rndquu Okay these can be removed safely, I will take them of them.

**Comment by 0x4007** [comment]
> What should be done:
> 
> * refactor all CI workflows in the https://github.com/ubiquity organization from `pull_request_target` to `pull_request`
> * fix related CI errors where necessary

This can probably be automated with a script locally: 
1. Recursive clone all repos
2. `sed` find and replace all `yml` files for `pull_request_target` 

```sh
sed 's/pull_request_target/pull_request/g' in.yml > in.yml
git commit -m "chore: pull_request_target to pull_request 
resolves https://github.com/ubiquity/cloudflare-deploy-action/issues/6"
git push
```

**Comment by gentlementlegen** [comment]
@0x4007 Didn't you open an issue about synching the templates? This should also solve that.

**Comment by 0x4007** [comment]
> @0x4007 Didn't you open an issue about synching the templates? This should also solve that.

https://github.com/ubiquity/ts-template/issues/54

**Comment by 0x4007** [comment]
> ```diff
> ! Failed to run comment evaluation. SyntaxError: Unexpected end of JSON input
> ```
> 

I think I'll need to add funds to the old bot as well because the new bot is unreliable. It broke twice tonight already

**Comment by gentlementlegen** [comment]
@0x4007 This was run again with the `max_length` fixed, see PR https://github.com/ubiquibot/conversation-rewards/pull/87

**Comment by 0x4007** [comment]
I think we should boost the conversation rewards.
