### ISSUE TITLE
Fix character encoding for output and echo the build URL

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/cloudflare-deploy-action#9]
When previews are deployed to Cloudflare, the echoed string has badly encoded characters printed to the console which make it not possible to use for subsequent steps:
```
$ /home/runner/work/_actions/ubiquity/cloudflare-deploy-action/main/node_modules/.bin/tsx src/index.ts --deployment_output 'yarn run v1.22.22%0A$ /home/runner/work/pay.ubq.fi/pay.ubq.fi/node_modules/.bin/wrangler pages deploy static --project-name pay-ubq-fi --branch development --commit-dirty=true%0AUploading... (54/55)%0AUploading... (55/55)%0A✨ Success! Uploaded 1 files (54 already uploaded) (3.53 sec)%0A%0A✨ Deployment complete! Take a peek over at https://712dfd43.pay-ubq-fi-bxp.pages.dev%0Adone/ in 8.21s.' --repository ubiquity/pay.ubq.fi --pull_request_number 214 --commit_sha 59f992f678124fe38736482f3a7ec8795fb5147a
```

 This is problematic to resolve https://github.com/ubiquity/pay.ubq.fi/pull/214

More details for the output:
https://github.com/ubiquity/pay.ubq.fi/actions/runs/8488898935/job/23258419415#step:2:259

**Comment by 0x4007** [comment]
Time estimate?

**Comment by gentlementlegen** [comment]
@pavlovcik Not sure how to estimate this, first time working on this project. Would have said on hour would be sufficient.

**Comment by 0x4007** [comment]
> @pavlovcik Not sure how to estimate this, first time working on this project. Would have said on hour would be sufficient.

CI related tasks are always slow to debug

**Comment by 0x4007** [comment]
Oh I understand the conversation reward bug now. You assumed two roles so it double counted

**Comment by gentlementlegen** [comment]
@pavlovcik You're right. Should hopefully fixed with the new workflow
